### PR TITLE
[Demos] Add demo URLs from a given folder.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/86)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/86)* status: LGTM missing from one of: emilieguth, Unresolved discussions (bin/ping_reviewers:r1 line 393)

___
*[bin/ping_reviewers, line 393 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/86#-Mj4RdX87kN-bFbQyc2E:-Mj4RdX98_GPayHMzyxz:bab03zc) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dcc0be90c53c92c46b38c78bb22df7e6c9561851/bin/ping_reviewers#L393)):*
> ```
>     if args.demo_url:
>         demos.append((args.demo_name, args.demo_url))
>     if args.folder:
> ```

shouldn't it be `args.directory` ?

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/86#-:-Mj4ioC_5YsrVna6c1t8:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r1 line 393)

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/86)* status: :shipit: complete! 0 of 2 files reviewed, 1 unresolved discussion

___
*[bin/ping_reviewers, line 393 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/86#-Mj4RdX87kN-bFbQyc2E:-Mj4punyCgHpkG6Uaymm:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dcc0be90c53c92c46b38c78bb22df7e6c9561851/bin/ping_reviewers#L393)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

shouldn't it be `args.directory` ?
</blockquote></details>

Done.

**Pull request merged**
