### PR TITLE
[Bug Fix] Make the links in github relative to root-dir.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/46)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-:-Mbu0bdH0mPS8nEHVIf3:bnfp4nl)* status: Missing an assignee or a reviewer, Unresolved discussions (bin/check_recent_todos:r1 line 41)

___
*[bin/check_recent_todos, line 41 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-Mbu0KW7565dg-k2NDSH:-Mbu0KW7565dg-k2NDSI:b-7rt81q) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/83fd4740e5786b427b1345d19bf38b73ea8c1f2a/bin/check_recent_todos#L41)):*
> ```
> 
> 
> @functools.lru_cache()
> ```

You don't need the `()`
___
*[bin/check_recent_todos, line 93 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-Mbu0Nyu-Y8NdEcLUHu7:-Mbu0Nyu-Y8NdEcLUHu8:bgh90d2) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/83fd4740e5786b427b1345d19bf38b73ea8c1f2a/bin/check_recent_todos#L93)):*
> ```
>     def format_for_slack(self) -> str:
>         """Format the _TodoRef for slack output."""
>         owner_text = f'{self.owner}: ' if self.owner else ''
> ```

Please add a blank line after the documentation

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/46)* status: Missing an assignee or a reviewer

___
*[bin/check_recent_todos, line 41 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-Mbu0KW7565dg-k2NDSH:-Mbu4FWp6uAN6UKvtywR:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/83fd4740e5786b427b1345d19bf38b73ea8c1f2a/bin/check_recent_todos#L41)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

You don't need the `()`
</blockquote></details>

Done.
___
*[bin/check_recent_todos, line 93 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-Mbu0Nyu-Y8NdEcLUHu7:-Mbu4Foh0QZZiaUHburb:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/83fd4740e5786b427b1345d19bf38b73ea8c1f2a/bin/check_recent_todos#L93)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a blank line after the documentation
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
+reviewer:@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/46#-:-Mbugv2G8MtzrLzfjsSW:b-4erzco)* status: :shipit: complete! 0 of 1 files reviewed, 2 unresolved discussions

**Pull request merged**
