### PR TITLE
[Tests] Add a test framework for ping_reviewers.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-:-MdTcRWM3Tn3u9izgfz0:bnfp4nl)* status: LGTM missing from one of: pcorpet

**Review by zozoens31 — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-:-MdTeT-o0LeqyZnIxKWY:b8b79qu)* status: LGTM missing from one of: pcorpet, Unresolved discussions (.circleci/config.yml:r2 line 13)

___
*[.circleci/config.yml, line 13 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdTeUTyAvFzGXIK29Ia:-MdTeUTyAvFzGXIK29Ib:bnfp4nl) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/93c9f6c671ae47b018556e70fe87ffaf149bafc3/.circleci/config.yml#L13)):*
> ```YAML
>           name: Test the python scripts
>           command: ls test/test_*.py | xargs -n1 python3
>   build:
> ```

:lgtm:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63)* status: LGTM missing from one of: pcorpet, Unresolved discussions (.circleci/config.yml:r2 line 13)

___
*[.circleci/config.yml, line 12 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWCtAWDpar1G39JBFp:-MdWCtAWDpar1G39JBFq:b-1nshc7) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/.circleci/config.yml#L12)):*
> ```YAML
>       - run:
>           name: Test the python scripts
>           command: ls test/test_*.py | xargs -n1 python3
> ```

Would you accept to use `nose` instead?
___
*[bin/ping_reviewers, line 22 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWD0iC13qK1hGyapTe:-MdWD0iC13qK1hGyapTf:b-bvedwd) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/bin/ping_reviewers#L22)):*
> ```
> 
> 
> class _Environment(NamedTuple):
> ```

I think it's more like a config than an env, the fact that you have a `from_env` is a strong indicator that this is not the env itself. Please rename the class or the method.
___
*[bin/ping_reviewers, line 23 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWDDouCaRn4o4Y6_A8:-MdWDDouCaRn4o4Y6_A9:b-7gyfxt) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/bin/ping_reviewers#L23)):*
> ```
> 
> class _Environment(NamedTuple):
>     github_repo: str
> ```

Good occasion to document those!
___
*[test/test_ping_reviewers.py, line 2 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWEDHc5yTt_5NaJiJK:-MdWEDHc5yTt_5NaJiJL:b-ttixb4) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/test/test_ping_reviewers.py#L2)):*
> ```Python
> #!/usr/bin/env python3
> """Tests for the ping_reviewers script."""
> ```

Either you're using python to test a script (that might not be in Python), then please make sure to be as much agnostic to the language the script is using XOR you are testing the python module, then call this file `ping_reviewers_test.py`
___
*[test/test_ping_reviewers.py, line 26 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWEbD443r8ZVhoij7V:-MdWEbD443r8ZVhoij7W:b-b0rqw) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/test/test_ping_reviewers.py#L26)):*
> ```Python
>         """No ping when Slack URL is not present."""
> 
>         self.assertFalse(ping_reviewers.main(env={'GITHUB_TOKEN': 'my-github-token'}))
> ```

I would prefer that we mock the http calls (with requests_mock) so that we are sure that no pings were sent.

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63)* status: LGTM missing from one of: pcorpet

___
*[.circleci/config.yml, line 12 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWCtAWDpar1G39JBFp:-MdWPHj35r2mvv91svNL:bnrf618) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/.circleci/config.yml#L12)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Would you accept to use `nose` instead?
</blockquote></details>

I'll do it later. This would probably require a difference environment (ie docker container) to avoid polluting our image with testing libs
___
*[bin/ping_reviewers, line 22 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWD0iC13qK1hGyapTe:-MdWPrKH4Hcj3SLyBb83:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/bin/ping_reviewers#L22)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think it's more like a config than an env, the fact that you have a `from_env` is a strong indicator that this is not the env itself. Please rename the class or the method.
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 23 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWDDouCaRn4o4Y6_A8:-MdXSnop1_kymQr-ZR8l:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/bin/ping_reviewers#L23)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Good occasion to document those!
</blockquote></details>

Done.
___
*[test/test_ping_reviewers.py, line 2 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWEDHc5yTt_5NaJiJK:-MdWOzZ36I-KMNIPtx0o:b-qftzi6) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/test/test_ping_reviewers.py#L2)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Either you're using python to test a script (that might not be in Python), then please make sure to be as much agnostic to the language the script is using XOR you are testing the python module, then call this file `ping_reviewers_test.py`
</blockquote></details>

Done. I'd love to test this as an agnostic script, but then I can't easily mock the requests...
___
*[test/test_ping_reviewers.py, line 26 at r4](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdWEbD443r8ZVhoij7V:-MdWPD1r7AOrm6aliF6E:brxwidl) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/c02f72b4824dc42d636fd5b39144fb017e0274fa/test/test_ping_reviewers.py#L26)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I would prefer that we mock the http calls (with requests_mock) so that we are sure that no pings were sent.
</blockquote></details>

Duly noted. Will do in another CL (when I have a proper test environment)

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-:-MdXVtSa38GD6sMVVNCG:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r8 line 25)

___
*[bin/ping_reviewers, line 25 at r8](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdXV3W946s_cyaMM_Jv:-MdXV3W946s_cyaMM_Jw:b-bt5bsx) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed546cc05a220f82da4fd3dea3f8a597a98e97c5/bin/ping_reviewers#L25)):*
> ```
>     # The full name of the changed github repository. Fetched from CircleCI environment.
>     github_repo: str
>     # A pairing between github user logins and Slack user IDs.
> ```

Please add blank lines between those so that it's more readable.
___
*[bin/ping_reviewers, line 210 at r8](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdXVodL87_A2zJdKufX:-MdXVodL87_A2zJdKufY:b7p740e) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed546cc05a220f82da4fd3dea3f8a597a98e97c5/bin/ping_reviewers#L210)):*
> ```
>     """Parse CLI arguments and ping reviewers.
> 
>     Return the number of ping sent (for testing purposes).
> ```

Please add a TODO to revert this change once the test is done differently

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/63)* status: :shipit: complete! all files reviewed, 3 unresolved discussions

___
*[bin/ping_reviewers, line 25 at r8](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdXV3W946s_cyaMM_Jv:-MdXdWxN8QlcosuoniAf:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed546cc05a220f82da4fd3dea3f8a597a98e97c5/bin/ping_reviewers#L25)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add blank lines between those so that it's more readable.
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 210 at r8](https://reviewable.io/reviews/bayesimpact/docker-circleci/63#-MdXVodL87_A2zJdKufX:-MdXdXU19kOUCrmZ2iRP:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed546cc05a220f82da4fd3dea3f8a597a98e97c5/bin/ping_reviewers#L210)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a TODO to revert this change once the test is done differently
</blockquote></details>

Done.

**Pull request merged**
