### PR TITLE
[Bazel] Add Bazel to docker image.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/97)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/97#-:-Mk1Wexo2yNwD4d7_Zj1:bnfp4nl)* status: Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-circleci/97#-Mk1WDu7DLq2cItI7vQ9:-Mk1WDu84D8bJ2LBeTjt:bcv4nwy) (no related file):*
Please check the size increase and add it to the commit message.

---

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/97)* status: :shipit: complete! 1 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-circleci/97#-Mk1WDu7DLq2cItI7vQ9:-Mk1kpYN1lCcQl5LgcMd:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please check the size increase and add it to the commit message.
</blockquote></details>

Done.

---

**Pull request merged**
