### PR TITLE
[CI] Update CI workflow for testing and building.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/101)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/101#-:-Mk2PxBO1KeymQkkU6r9:bnfp4nl)* status: Unresolved discussions (.circleci/config.yml:r1 line 74)

___
*[.circleci/config.yml, line 74 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/101#-Mk2PqEiA-Y1ziT5GI72:-Mk2PqEiA-Y1ziT5GI73:bt0g8f8) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/1ce94f7a21343fa388f40e05083f6ba800fdb3a8/.circleci/config.yml#L74)):*
> ```YAML
>             - test
>             - test-build
>       - build:
> ```

Let's group the two builds and add a comment for each:
`Not for main`
`for main: build and publish`

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/101)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[.circleci/config.yml, line 74 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/101#-Mk2PqEiA-Y1ziT5GI72:-Mk2SJIT42ddB1h2jwH3:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/1ce94f7a21343fa388f40e05083f6ba800fdb3a8/.circleci/config.yml#L74)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Let's group the two builds and add a comment for each:
`Not for main`
`for main: build and publish`
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
