### PR TITLE
[Bug Fix] Account for unexpected parsing errors in check_recent_todos.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/41)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-:-MbMWcEM73i4aRC0quJH:bnfp4nl)* status: Unresolved discussions (bin/check_recent_todos:r1 line 44)

___
*[bin/check_recent_todos, line 44 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-MbMWJrL-78QQWdDGWf-:-MbMWJrL-78QQWdDGWf0:bf5fe8l) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/0b25b85537921857a323015b5ae157760d7a97d0/bin/check_recent_todos#L44)):*
> ```
> 
>     @staticmethod
>     def parse_line(todo_line: str) -> '_TodoRef':
> ```

Optional['_TodoRef']
___
*[bin/check_recent_todos, line 75 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-MbMWRGo8iJ3FeT8361c:-MbMWRGo8iJ3FeT8361d:b-nddsn8) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/0b25b85537921857a323015b5ae157760d7a97d0/bin/check_recent_todos#L75)):*
> ```
>         line
>         for todo_line in _grep_all_todos(folder) if todo_line.strip()
>         for line in [_TodoRef.parse_line(todo_line)] if line]
> ```

Ouch, I find this quite ugly. Please revert the logic and make that a generator instead of returing a lilst. That can help you prevent a yield ore easily
___
*[bin/check_recent_todos, line 92 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-MbMWa63AvfvVDWegzrQ:-MbMWa645HEY-F_uxBFI:b-cavh3r) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/65ae1ba7cbdbedda606643bd0f69481a8f8a1028/bin/check_recent_todos#L92)):*
> ```
>         'text': f'{_PROJECT_USERNAME}/{_PROJECT_REPONAME} TODOs modifications since {duration}.\n'
>         f'{closed_todos_count} TODOs removed\n{len(new_todos)} TODOs added:\n' + todos_added,
>         'channel': '@cyrille',
> ```

muhahah

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/41)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[bin/check_recent_todos, line 44 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-MbMWJrL-78QQWdDGWf-:-MbM_8TQ5tGEiSI4v9Bw:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/0b25b85537921857a323015b5ae157760d7a97d0/bin/check_recent_todos#L44)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Optional['_TodoRef']
</blockquote></details>

Done.
___
*[bin/check_recent_todos, line 75 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/41#-MbMWRGo8iJ3FeT8361c:-MbM_8qr9ISXB26MCyOk:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/0b25b85537921857a323015b5ae157760d7a97d0/bin/check_recent_todos#L75)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Ouch, I find this quite ugly. Please revert the logic and make that a generator instead of returing a lilst. That can help you prevent a yield ore easily
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
