### PR TITLE
[Ping] Add more information when missing some parameters.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/51)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by silendale — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/51#-:-MdGl6SX6YIuXMT7SFIw:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r1 line 152)

___
*[bin/ping_reviewers, line 152 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/51#-MdGl3O_0Va2cIZj1-8Y:-MdGl3O_0Va2cIZj1-8Z:bxtub52) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/b5d7f2132ac3c1916ba2f68ddac615063809269d/bin/ping_reviewers#L152)):*
> ```
> 
>     parser = argparse.ArgumentParser(
>         description='Ping reviewers for the current PR.')
> ```

Is it needed?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/51)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[bin/ping_reviewers, line 152 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/51#-MdGl3O_0Va2cIZj1-8Y:-MdGq8NG9TCKRIvIf8jP:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/b5d7f2132ac3c1916ba2f68ddac615063809269d/bin/ping_reviewers#L152)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
