### PR TITLE
[Todos] Check TODOs only by file and text.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39)* status: LGTM missing from one of: pcorpet, Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-Mam8hlW2hPxgvjlF0YM:-Mam8hl_9OOJn7tD2g7K:b7oj20f) (no related file):*
I think I prefer having one line per TODO

---
___
*[bin/check_recent_todos, line 27 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-Mam8fAi29LgFbe8hW6d:-Mam8fAj1a7rA-ZnPTsc:b-tvy5mw) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/6f29e21cc0ec01480bab36ad53ae67e997fa68a9/bin/check_recent_todos#L27)):*
> ```
> readonly TODOS_ADDED="$(mktemp)"
> cat "$PAST_TODOS_FILE" "$PAST_TODOS_FILE" "$RECENT_TODOS_FILE" | sort | uniq -u \
>     | sed -e 's/\W*TODO\((.*)\)\?: \?\(.*\)$/\\\n  TODO\1: *\2*/' \
> ```

I think this introduces an extra `\` at the end of the file line.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/check_recent_todos:r1 line 27)

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-Mam8hlW2hPxgvjlF0YM:-MbDu-t9-ub7Ls-Vl-8D:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think I prefer having one line per TODO
</blockquote></details>

Done.

---

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39)* status: LGTM missing from one of: pcorpet

___
*[bin/check_recent_todos, line 27 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-Mam8fAi29LgFbe8hW6d:-MbDuFE260GblVcyCzet:b-848932) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/6f29e21cc0ec01480bab36ad53ae67e997fa68a9/bin/check_recent_todos#L27)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think this introduces an extra `\` at the end of the file line.
</blockquote></details>

Moot.

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-:-MbHNhaRCUy7qbOOfukQ:bnfp4nl)* status: Unresolved discussions (bin/check_recent_todos:r2 line 51)

___
*[bin/check_recent_todos, line 51 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-MbHMvzS-YpN7T7CAjlA:-MbHMvzS-YpN7T7CAjlB:b-yphrum) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/6da1590835757374e5417e4e9fa6f7ec72399416/bin/check_recent_todos#L51)):*
> ```
> 
> 
> def _parse_todo(todo: str) -> _TodoRef:
> ```

Please move to the class as a `@staticmethod`

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/39)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[bin/check_recent_todos, line 51 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/39#-MbHMvzS-YpN7T7CAjlA:-MbIhMtqEghsk8njOVNr:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/6da1590835757374e5417e4e9fa6f7ec72399416/bin/check_recent_todos#L51)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please move to the class as a `@staticmethod`
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
