### PR TITLE
[Clean Code] Use argparse for check_recent_todos.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/82)

### CODE REVIEW

**Comment by pcorpet** [comment]
:rocket:

**Review by zozoens31 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/82#-:-MiQT4la6N2Bpqga8dTE:bnfp4nl)* status: Unresolved discussions (bin/check_recent_todos:r1 line 135)

___
*[bin/check_recent_todos, line 135 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/82#-MiQTO-B-en-iZdKYBqW:-MiQTO-B-en-iZdKYBqX:bnu9tpr) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed3a7c5db35daccfb3863a496a7d40b01088dbcf/bin/check_recent_todos#L135)):*
> ```
> 
> 
> def main(string_args: Optional[Sequence[str]] = None) -> None:
> ```

please, use `List` instead of `Sequence` to avoid additional import. The feature is not used anyways...

**Comment by pcorpet** [comment]
:rocket:

**Review by pcorpet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/82)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[bin/check_recent_todos, line 135 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/82#-MiQTO-B-en-iZdKYBqW:-MiQw5RH7w5BHNIXX1Tk:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ed3a7c5db35daccfb3863a496a7d40b01088dbcf/bin/check_recent_todos#L135)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, use `List` instead of `Sequence` to avoid additional import. The feature is not used anyways...
</blockquote></details>

Done.

**Pull request merged**
