### PR TITLE
[Clean Code] Use a docker tag for gcloud install.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/100)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/100)* status: LGTM missing from one of: pcorpet

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-circleci/100#-Mk1yz_DD4oQR-sELcII:-Mk1yz_DD4oQR-sELcIJ:b-b8agvb) (no related file):*
FYI https://reviewable.io/reviews/bayesimpact/cas-contact-internal/1454#-

---

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/100#-:-Mk2HWX_1z_pAPOM6JVG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
