### PR TITLE
[Slack] Ping slack reviewers.

### PR DESCRIPTION
**Pull request by zozoens31**
Code generally imported from bayesimpact/fdr

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/49)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-:-Md45Ht0D0tu_VSGUwS5:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r1 line 19)

___
*[bin/ping_reviewers, line 19 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md442eV5kIWIVT9xr70:-Md442eV5kIWIVT9xr71:b-hj4t2s) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L19)):*
> ```
> _PR_NUMBER = os.getenv('CIRCLE_PULL_REQUEST', '').rsplit('/', 1)[-1]
> 
> _SLACK_TO_GITHUB: dict[str, str] = json.loads(os.getenv('SLACK_GITHUB_USER_PAIRINGS', r'{}'))
> ```

Please document
___
*[bin/ping_reviewers, line 72 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44E4REb1WEtyDWLKK:-Md44E4REb1WEtyDWLKL:bovvp5q) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L72)):*
> ```
>         return f'<@{user_id}>'
>     except KeyError:
>         return f'@{_SLACK_TO_GITHUB.get(github_user, github_user)}'
> ```

what about the as_channel case?
___
*[bin/ping_reviewers, line 85 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44RgD-pHPb7_I2ZV-:-Md44RgD-pHPb7_I2ZV0:b6dcbtd) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L85)):*
> ```
>         github_reviewer: Optional[str] = None, reviewers: Optional[str] = None) -> None:
>     request: _Request = {
>         'text': f'A <{demo_url}|demo> is ready' if demo_url else 'CI tests passed'
> ```

Please add the author of the PR, at least a TODO
___
*[bin/ping_reviewers, line 100 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44aDS8jhLAEIz4g4m:-Md44aDS8jhLAEIz4g4n:b-wmjvyp) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L100)):*
> ```
>     """Send slack pings to the relevant people, if requirements are met."""
> 
>     string_args = string_args or sys.argv[1:]
> ```

Use argparse please
___
*[bin/ping_reviewers, line 106 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44jyX3KP9QoV6r5HX:-Md44jyX3KP9QoV6r5HY:b-i1tbmp) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L106)):*
> ```
>         return
>     if not _GITHUB_TOKEN:
>         print('Need a Github token to push, please set GITHUB_TOKEN')
> ```

What do you need to push? Did you mean to get the pull request info?
___
*[bin/ping_reviewers, line 129 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md458iX-SypL0g06Gbv:-Md458iY0nnJEhQYl_hg:b5wvtaf) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L129)):*
> ```
>     if not all_reviewers:
>         return
>     logging.info('Pinging reviewers (of #%d) on Slack to tell them the Demo is ready…', _PR_NUMBER)
> ```

PR_NUMBER is a string

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/49)* status: :shipit: complete! 0 of 1 files reviewed, 6 unresolved discussions

___
*[bin/ping_reviewers, line 19 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md442eV5kIWIVT9xr70:-Md9FuzSBiYvB5u_1pON:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L19)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 72 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44E4REb1WEtyDWLKK:-Md9CiQM74-ITPAXDBsA:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L72)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

what about the as_channel case?
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 85 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44RgD-pHPb7_I2ZV-:-Md9D5tuCiYFV69_wyzT:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L85)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add the author of the PR, at least a TODO
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 100 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44aDS8jhLAEIz4g4m:-Md9EcecAiutXIObLOnc:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L100)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Use argparse please
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 106 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md44jyX3KP9QoV6r5HX:-Md9DWRo4u7go0PGrmJk:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L106)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

What do you need to push? Did you mean to get the pull request info?
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 129 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/49#-Md458iX-SypL0g06Gbv:-Md9DQEL6w72A8nyxSJf:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/dfc57913b3eacf305c9453f35c31a8f80e3081ac/bin/ping_reviewers#L129)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

PR_NUMBER is a string
</blockquote></details>

Done.

**Pull request merged**
