### PR TITLE
Use correct directory to place scripts

### PR DESCRIPTION
**Pull request by florianjourda**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/7)

### CODE REVIEW

**Comment by florianjourda** [comment]
+@pcorpet 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7#-:-KwkefXXHyjSK6_jECEW:bv2wshd)*

**Comment by florianjourda** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7#-Kwkej87iGsgY-JnSiWE:-Kwkej87iGsgY-JnSiWF:bd14crp) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2d3b0a42f75fc824785bf00a82ffb64ebbc9d5/Dockerfile#L10)):*
> ```Dockerfile
>   pip install docker-compose proselint requests shyaml
> 
> WORKDIR /project
> ```

this was conflicting with CircleCI (and even it should have been /work/project) so I decide to move the scripts as commands to usr/bin instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7#-Kwkej87iGsgY-JnSiWE:-Kwni8rQJ6PmVBXshuiL:byucyi2) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2d3b0a42f75fc824785bf00a82ffb64ebbc9d5/Dockerfile#L10)):*
<details><summary><i>Previously, florianjourda (Florian Jourda) wrote…</i></summary><blockquote>

this was conflicting with CircleCI (and even it should have been /work/project) so I decide to move the scripts as commands to usr/bin instead
</blockquote></details>

please don't change the workdir and move the shell script directly to /usr/bin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7#-:-KwniDv1-8McFdO9Y-tk:bnfp4nl)*

**Comment by florianjourda** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7#-Kwkej87iGsgY-JnSiWE:-KwoTk3yAny6yJAEgCLW:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2d3b0a42f75fc824785bf00a82ffb64ebbc9d5/Dockerfile#L10)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

please don't change the workdir and move the shell script directly to /usr/bin
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-circleci/7)*

**Pull request merged**
