### PR TITLE
[Ping] Get PR from sha1 when CIRCLE_PULL_REQUEST doesn't exist.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/72)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/72#-:-Mdr3MBp5G-kK17HX3hB:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r1 line 182)

___
*[bin/ping_reviewers, line 182 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/72#-Mdr325jCU33-OPNJsyw:-Mdr325jCU33-OPNJsyx:b-xzpjpr) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02dcb88fc2ac5f6e08405edcdf5d42c0dfa971d1/bin/ping_reviewers#L182)):*
> ```
> 
> 
> def _get_query(config: _Config, should_ping_stale: bool) -> Optional[str]:
> ```

Please rename to explain what is the responsibility of this function.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/72)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[bin/ping_reviewers, line 182 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/72#-Mdr325jCU33-OPNJsyw:-Mdr9wuTDG_Y71SWZG6B:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02dcb88fc2ac5f6e08405edcdf5d42c0dfa971d1/bin/ping_reviewers#L182)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please rename to explain what is the responsibility of this function.
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
