### PR TITLE
[Scripts] Add useful scripts.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/20)

### CODE REVIEW

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-:-M4uW9xm8Q1PxRD5bcnH:bnfp4nl)* status: Unresolved discussions (bin/check_fresh_release:r1 line 1)

___
*[bin/check_fresh_release, line 1 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVgIABxULHrAhAeKH:-M4uVgIABxULHrAhAeKI:b-hj4t2s) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/check_fresh_release#L1)):*
> ```
> #!/bin/bash
> ```

Please document
___
*[bin/check_recent_todos, line 1 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVhcKBNG8EypjuxEf:-M4uVhcL4qaVlpK4QPh9:b-hj4t2s) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/check_recent_todos#L1)):*
> ```
> #!/bin/bash
> ```

Please document
___
*[bin/get_demo_vars, line 4 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVmh_Co5mY4yl0IRp:-M4uVmh_Co5mY4yl0IRq:b-ok0eyh) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/get_demo_vars#L4)):*
> ```
> # Specify which vars should be set on the demo run from the current build.
> #
> # Assumes that it is run in circleCI context.
> ```

Please add an example

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/20)* status: Unresolved discussions (bin/get_demo_vars:r1 line 4)

___
*[bin/check_fresh_release, line 1 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVgIABxULHrAhAeKH:-M4xlwUFDK1571u-C8nr:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/check_fresh_release#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.
___
*[bin/check_recent_todos, line 1 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVhcKBNG8EypjuxEf:-M4xlwy3142HGhEMxRyC:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/check_recent_todos#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/20)* status: Unresolved discussions (bin/get_demo_vars:r1 line 4)

___
*[bin/check_fresh_release, line 6 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4xz2yuCrKctUBLRO_v:-M4xz2yuCrKctUBLRO_w:bzfx8nx) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/64385c48438b17f8ce41879b2fd034799c268057/bin/check_fresh_release#L6)):*
> ```
> # Run using check_fresh_release branch duration [folder]
> #       - branch is the name of the branch where the released version is at
> #       - duration is a `date` readable duration, for which it is admitted to have non-released code.
> ```

100 chars max please
___
*[bin/check_fresh_release, line 8 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4xz6GI2qvKQLYVg0WZ:-M4xz6GI2qvKQLYVg0W_:b-2guby3) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/64385c48438b17f8ce41879b2fd034799c268057/bin/check_fresh_release#L8)):*
> ```
> #       - duration is a `date` readable duration, for which it is admitted to have non-released code.
> #           e.g. '14 days'
> #       - folder is a subfolder of the repository to which we restrict the search of changes since release.
> ```

same here

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/20)* status: :shipit: complete! 3 of 7 files reviewed, 5 unresolved discussions

___
*[bin/check_fresh_release, line 6 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4xz2yuCrKctUBLRO_v:-M57GRxc1Ec4jW0tFgWj:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/64385c48438b17f8ce41879b2fd034799c268057/bin/check_fresh_release#L6)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

100 chars max please
</blockquote></details>

Done.
___
*[bin/check_fresh_release, line 8 at r2](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4xz6GI2qvKQLYVg0WZ:-M57GSGO6LKcNlPrJ7_0:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/64385c48438b17f8ce41879b2fd034799c268057/bin/check_fresh_release#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[bin/get_demo_vars, line 4 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/20#-M4uVmh_Co5mY4yl0IRp:-M57GFeE9w80z2RFfo5X:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/883bd4299f8f7e96e913fabf438dc6b4ecffe7cc/bin/get_demo_vars#L4)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add an example
</blockquote></details>

Done.

**Pull request merged**
