### PR TITLE
[Clean Code] Add an extension to all python scripts.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/92)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/92#-:-MjdDc3K0CtKPD5lGCOu:bnfp4nl)* status: Unresolved discussions (Dockerfile:r1 line 33)

___
*[Dockerfile, line 33 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/92#-MjdDRHqCMiCUEAC1tSf:-MjdDRHqCMiCUEAC1tSg:b-pfvhqf) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/4837117d19a2e9dc053915c4c96559cc5e788c21/Dockerfile#L33)):*
> ```Dockerfile
> 
> # Adding gcloud and binaries to the path
> ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin:/usr/local/circleci/bin
> ```

did you mean /usr/share/?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/92)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[Dockerfile, line 33 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/92#-MjdDRHqCMiCUEAC1tSf:-MjdEMvy5yz6NpbJGfVL:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/4837117d19a2e9dc053915c4c96559cc5e788c21/Dockerfile#L33)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

did you mean /usr/share/?
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
