### PR TITLE
[Ping] Check Github statuses before pinging.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/74)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/74)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/ping_reviewers:r1 line 58)

___
*[bin/ping_reviewers, line 58 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsXio2-cSi8IFa_YXV:-MdsXio37GSCWQkWql0Z:b-hj4t2s) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L58)):*
> ```
> 
> class _ReviewInfo(NamedTuple):
>     should_review: bool
> ```

Please document
___
*[bin/ping_reviewers, line 116 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsYAlZ4Y_jjUXaDs5d:-MdsYAlZ4Y_jjUXaDs5e:b-hj4t2s) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L116)):*
> ```
> 
> 
> _PULL_REQUEST_INFO_GRAPHQL_QUERY = '''query($prNodeId: ID!) {
> ```

Please document
___
*[bin/ping_reviewers, line 139 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsXzZF7f38OR_DmzY8:-MdsXzZF7f38OR_DmzY9:b9bkg71) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L139)):*
> ```
>     }
> }'''
> _Context = TypedDict('_Context', {'context': str, 'targetUrl': str}, total=False)
> ```

This looks like we should build a separate pip library with Github type... if it doesn't exist already.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/74)* status: LGTM missing from one of: pcorpet

___
*[bin/ping_reviewers, line 58 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsXio2-cSi8IFa_YXV:-Me-aDoZAkzxpvCipj7W:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L58)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 116 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsYAlZ4Y_jjUXaDs5d:-Me-apz00JGi3qmr-JP6:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L116)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.
___
*[bin/ping_reviewers, line 139 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-MdsXzZF7f38OR_DmzY8:-Me-Ymaf81PbVxsY_ogO:b-utngzk) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2f2aa6772ff1ade33310823bd7ddb71e93dbc515/bin/ping_reviewers#L139)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This looks like we should build a separate pip library with Github type... if it doesn't exist already.
</blockquote></details>

It does look like it... That's why I've started building it.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/74#-:-Me0EjmLA-gOHTHNWuW8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
