### PR TITLE
[Demo Vars] Add release variables to the demo vars.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/77)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/77)* status: LGTM missing from one of: pcorpet, Unresolved discussions (test/get_demo_vars_test.py:r1 line 155)

___
*[test/get_demo_vars_test.py, line 155 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/77#-MeadiFB4pX4gSNKkJLq:-MeadiFB4pX4gSNKkJLr:b-od52iw) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2b05262b262c115071ec515df8724d1190118466/test/get_demo_vars_test.py#L155)):*
> ```Python
>         })
>         self.assertEqual(
>             'repo=bayes%2Fbob&release=my-tag&'
> ```

Are you going to send those to FDR as well? Why is it needed as a "demo" var?

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/77)* status: LGTM missing from one of: pcorpet, Unresolved discussions (test/get_demo_vars_test.py:r1 line 155)

___
*[test/get_demo_vars_test.py, line 155 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/77#-MeadiFB4pX4gSNKkJLq:-Mnyt8i57NjgzE98xMWZ:b32wyo) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2b05262b262c115071ec515df8724d1190118466/test/get_demo_vars_test.py#L155)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Are you going to send those to FDR as well? Why is it needed as a "demo" var?
</blockquote></details>

up

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/77)* status: LGTM missing from one of: pcorpet, Unresolved discussions (test/get_demo_vars_test.py:r1 line 155)

___
*[test/get_demo_vars_test.py, line 155 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/77#-MeadiFB4pX4gSNKkJLq:-MvIWe_g8a2AlCu9UsHy:b32wyo) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/2b05262b262c115071ec515df8724d1190118466/test/get_demo_vars_test.py#L155)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

up
</blockquote></details>

up

**Pull request closed without merging**
