### PR TITLE
[CI] Ping reviewers at the end of the tests.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/65)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/65#-:-MdXmJRPBO9DGWarN_l3:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
