### PR TITLE
[Clean Code] Proper types for get_demo_var and its tests.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/75)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/75#-:-MeacuBQ5SaBBkw5hv3a:bnfp4nl)* status: Unresolved discussions (bin/ping_reviewers:r1 line 67)

___
*[bin/ping_reviewers, line 67 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/75#-Meacew33q9yArVVssrT:-Meacew33q9yArVVssrU:b2nhdxu) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ac8c01e1279207687c8d26e2574a9add0072b2cf/bin/ping_reviewers#L67)):*
> ```
>     should_review: bool
> 
>     # The action the PR author should take, if any.
> ```

FAR

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/75)* status: :shipit: complete! 2 of 3 files reviewed, 1 unresolved discussion

___
*[bin/ping_reviewers, line 67 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/75#-Meacew33q9yArVVssrT:-MedOwn0EuP5o3V4Cr8N:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/ac8c01e1279207687c8d26e2574a9add0072b2cf/bin/ping_reviewers#L67)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

FAR
</blockquote></details>

Done.

**Pull request merged**
