### PR TITLE
[Demos] Show demos from Github deployments in Github statuses.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/93)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/93#-:-MjngDyI0mYeVQ7cGhYI:bnfp4nl)* status: Unresolved discussions (bin/create_demo_statuses.py:r1 line 72)

___
*[bin/create_demo_statuses.py, line 72 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/93#-MjnfuhB6LU3C53O0JlC:-MjnfuhB6LU3C53O0JlD:b-ie2o35) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/94fe9826003e42f3b07423a3321a76893ebfff3a/bin/create_demo_statuses.py#L72)):*
> ```Python
>     """Create a Github status for the given demo."""
> 
>     print(name, url)
> ```

was this `print` instruction intended?

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/93)* status: :shipit: complete! 0 of 2 files reviewed, 1 unresolved discussion

___
*[bin/create_demo_statuses.py, line 72 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/93#-MjnfuhB6LU3C53O0JlC:-MjnpCIS3trUruoO6aIb:b3bkgc1) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/94fe9826003e42f3b07423a3321a76893ebfff3a/bin/create_demo_statuses.py#L72)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

was this `print` instruction intended?
</blockquote></details>

Done. Indeed not

**Pull request merged**
