### PR TITLE
[CD] Build and push docker image on default branch.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/61)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/61)* status: LGTM missing from one of: pcorpet, Unresolved discussions (.circleci/config.yml:r1 line 36)

___
*[.circleci/config.yml, line 36 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/61#-MdSGfRo3JmYkraxCaTi:-MdSGfRo3JmYkraxCaTj:b-85x9up) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02249a8556e284ca166bcab513769f2c3ae95ba0/.circleci/config.yml#L36)):*
> ```YAML
> workflows:
>   version: 2
>   test:
> ```

Please rename.
___
*[.circleci/config.yml, line 66 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/61#-MdSGcZUB2tJrDEHxLsy:-MdSGcZUB2tJrDEHxLsz:b-cv2pp5) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02249a8556e284ca166bcab513769f2c3ae95ba0/.circleci/config.yml#L66)):*
> ```YAML
>                 - main
>     jobs:
>       - build:
> ```

Do you still need this one then?

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/61)* status: LGTM missing from one of: pcorpet

___
*[.circleci/config.yml, line 36 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/61#-MdSGfRo3JmYkraxCaTi:-MdSMFyRESevNB1ZYAhr:b-896fix) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02249a8556e284ca166bcab513769f2c3ae95ba0/.circleci/config.yml#L36)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please rename.
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 66 at r1](https://reviewable.io/reviews/bayesimpact/docker-circleci/61#-MdSGcZUB2tJrDEHxLsy:-MdSMGIG9F4aIN2BlT7r:b-pqbwpy) ([raw file](https://github.com/bayesimpact/docker-circleci/blob/02249a8556e284ca166bcab513769f2c3ae95ba0/.circleci/config.yml#L66)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Do you still need this one then?
</blockquote></details>

Yes, to update the base image to a recent one when there are no changes on main.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-circleci/61#-:-MdSYbZ08SUoYkJQx5cL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
